name: Qodana Scan

on:
  workflow_dispatch:  # Allow manual trigger
  push:  # Trigger on push to any branch
    branches:
      - '*'  # The wildcard (*) means all branches
  pull_request:  # Trigger on pull requests
    branches:
      - '*'  # Trigger for any pull request across all branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3

      # Run Qodana scan with custom .qodana.yml configuration
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          config-file: .qodana.yml  # Path to your custom Qodana configuration file

      # Clean up after scan
      - name: Clean up
        run: |
          sudo apt-get clean
          sudo rm -rf /tmp/*
